### ISSUE TITLE
Bad Practice for hashing passwords

### ISSUE THREAD

**Issue by ghost** [vapor/auth-template#3]
In the Auth Template example it uses the `drop.hash` to create a hashed password, which is configured to use a SHA256 hasher. This is not secure! To make it explicit, the `passwordVerifier` on the `User` should use a `BCryptHasher` to show best practises.

**Comment by tanner0101** [comment]
Oops. No idea how that happened. It's supposed to be using the BCrypt hasher (hence the `bcrypt.json` file).
