### ISSUE TITLE
Postman returns invalidCredentials when posting to Login method

### ISSUE THREAD

**Issue by fvvliet** [vapor/auth-template#7]
When using Postman to test this REST API, I keep getting 'invalidCredentials' error when calling the 'Login' method (with Basic Auth header key). For some reason the verify() in Hash extension of BCrypt 1.1.0 dependency fails but I don't know why (I use PostgreSQL to save the User & Token data).

Anyone any idea how to fix this ?

thanks in advance
Frank

**Comment by 0xTim** [comment]
@fvvliet when you say you use Postgres to save the user and token data - how are you saving the user's password? Have you hashed it with BCrypt?

**Comment by fvvliet** [comment]
@0xTim : the password is hashed but this is all done by the template code.

**Comment by 0xTim** [comment]
@fvvliet I've just built and tested the current API template and had no issues. Can you confirm that the user exists in the Postgres table before you send the request? (The password should look like `$2a$10$Z.EFPZrT0Atyrzvx.vfzJuDFImU9h5thpOyVa0KKd0WIy3nmIehxS` after hashing) And what does the header look like that you are sending?

**Comment by fvvliet** [comment]
@0xTim , yes the user exists when sending request 'Login'. The password is hashed. The header looks like in the attachments.
<img width="1086" alt="screen shot 2018-02-27 at 10 06 55" src="https://user-images.githubusercontent.com/2924822/36719712-2cb958d4-1ba6-11e8-95fa-2b3f0aa46cee.png">

**Comment by fvvliet** [comment]
<img width="866" alt="screen shot 2018-02-27 at 10 05 50" src="https://user-images.githubusercontent.com/2924822/36719741-4536ef98-1ba6-11e8-854a-94b9d45d4f82.png">
<img width="872" alt="screen shot 2018-02-27 at 10 06 01" src="https://user-images.githubusercontent.com/2924822/36719748-48677f66-1ba6-11e8-852c-40a172a04562.png">

**Comment by 0xTim** [comment]
You should pass your plaintext password as the password in the auth header!

**Comment by fvvliet** [comment]
Yes that's it. Thanks for your help !
