### ISSUE TITLE
Request to add client tests on routes

### ISSUE THREAD

**Issue by riyadshauk** [vapor/auth-template#9]
Please add tests in auth-template/Tests/AppTests/AppTests.swift.

I'm having difficulty sending simple HTTP POST and GET requests as a Vapor client from within AppTests.swift and would really benefit from seeing it exemplified here. For instance, I cannot call `Droplet()` even after I `import Vapor`.

So far, I'm trying to do some basic BDD (Node.js + Express with mocha/chai/jasmine inspired-style):

```
import Quick
import Nimble
import Vapor

@testable import App

class RoutesSpec: QuickSpec {
    
    let testUrl = "http://localhost:8080"
    
    override func spec() {
        describe("User can create account") {
            it("should respond with error JSON when an incorrect body is sent") {
                
                // @todo use Vapor to make simple HTTP POST here
                
                do {
                    // @todo .....
                    // (I've tried looking in the Vapor documentation... 
                    // I'm still unsure how to make simple HTTP requests...
                    // Request for example here...) ??
                } catch {
                    print("Error")
                }
                
                expect(false).toEventually(beTrue())
            }
            
            it("should respond respond with a user JSON when a correct body is sent") {
                // (@todo ....)                
                expect(false).toEventually(beTrue())
            }
            
        }
        
        
    }
}
```

**Comment by tanner0101** [comment]
There are quite a few ways to do this. The simplest is to create a configured instance of your `Application`, then use that to create a `Responder` that can convert `Request` to `Response`. 

You can see some examples of that here: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ApplicationTests.swift

(specifically https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ApplicationTests.swift#L783-L792)

We're hoping to include some basic testing helpers with Vapor soon. Probably in the next version. Once we decide on what that will look like, I think it will make sense to start including tests in the templates. 👍

**Comment by riyadshauk** [comment]
Thanks. That's a nice reference to look to... but when I try to run a POST request example / aka when I copy-paste the `testParameter` function, I get a compile error on line one of that function, in Xcode: `"Type 'Application' has no member 'runningTest'; did you mean 'runningServer'?"`. (However, when I copy-paste `testContent` and run that test case in XCTestCase format, the `testContent` test passes)....

So, I have a working GET example, but not a working POST example, from that file...

(and when I try to run the POST request example supplied in ClientTests.swift, I get an error on this line: `return Future.map(on: req) { req.response() }`, saying `"Value of type 'Request' has no member 'response'"`).....

I'd really appreciate a working POST request example / test-case to get going with.

**Comment by riyadshauk** [comment]
Awesome. Very sexy testing style; using fancy Validations – starting to get the hang of it (and it works with testing both GET and POST). This is why I chose to use a framework (ie Vapor) to get up and running with server-side Swift fast: get some nice design patterns and conventions without needing to come up with modular and elegant solutions on my own. Thanks for your time and help : ) (and sorry for my ignorance in not knowing where exactly to look in the test files earlier... Lesson learned for next time)

**Comment by riyadshauk** [comment]
For what it's worth, for anybody else interested in seeing a working example, this works as a somewhat minimal example for now, using the private extensions found from this point onward: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ApplicationTests.swift#L783-L792 (linked from Tanner's response):

```
import Vapor
import XCTest

@testable import App

class RouteTests: XCTestCase {
    func testUserCreationInvalidPasswordVerification() throws {
        try Application.makeTest { router in
            router.post(CreateUserRequest.self, at: "users") { req, user -> String in
                let userController = UserController()
                let userResponseFuture = try userController.create(req)
                var status = "ok"
                userResponseFuture.whenFailure({ (Error) in
                    if Error.localizedDescription.contains("Password and verification must match.") {
                        status = "invalid password"
                    }
                })
                if status == "invalid password" {
                    throw Abort(.badRequest, reason: "Password and verification must match.")
                }
                return status
            }
            }.test(.POST, "users", beforeSend: {
                try $0.content.encode(["name": "riyad", "password": "123", "verifyPassword": "no", "email": "a@b.com"])
            }, afterSend: { res in
                XCTAssertEqual(res.http.status, .badRequest)
                XCTAssert(res.http.body.string.contains("Password and verification must match."))
            })
    }
}
```

I'm not sure if this is the best test design, but it gets the job done for now. Any thoughts? Thanks again, @tanner0101 .

**Comment by 0xTim** [comment]
Also see https://github.com/raywenderlich/vapor-til/tree/master/Tests/AppTests
